services:
  backend:
    build:
      context: ./scikgdash-backend
      dockerfile: Dockerfile
    image: registry.gitlab.com/lenaj/scikgdash/curation-dashboard-backend
    container_name: scikgdash-backend
    ports:
      - "8001:8001"
    env_file:
      - ./scikgdash-backend/default.env
      - ./scikgdash-backend/.docker.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    networks:
      - app-network
    #user: "1001:1001"
    volumes:
      - "./scikgdash-backend/data:/data"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/lenaj/scikgdash/curation-dashboard-frontend
    container_name: scikgdash-frontend
    ports:
      - "3000:3000"
    env_file:
      - default.env
      - .docker.env
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    #user: "1001:1001"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

