import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import SideNav from "./components/layout/SideNav";
import Header from "./components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <div className="flex flex-1">
            <SideNav />
            <main className="flex-1 ps-12 p-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
